[package]
name = "bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev.package.bindings]
opt-level = 3
debug = 0

[dependencies]
windows = "0.19"

[build-dependencies]
windows = "0.19"